### PR TITLE
Add support for loading specific bindings file by specifying path in …

### PR DESCRIPTION
**Pull request by Guntereno**
When playing the Odyssey alpha, I found the existing plugin didn't detect my updated keybinds. This seems to be because the regex that finds it expects a "3.0" binding file name. I considered updating this to detect any digit in that position, but then it would always detect the '4.0' bindings, even when I want to go back and play the base game.

Here I allow the user to specify an explicit path in the context. This allows me to create a 'Sync bindings for Odyssey' command, and use a 'loadbinds' command to reset to use the 3.0 binds.

### CODE REVIEW

**Comment by alterNERDtive** [comment]
Hi! Thanks for taking the time to look into this. First of all, Odyssey alpha is basically over, so I won’t update anything for that anymore. And then we’re actually talking about two separate things here:

1. Odyssey support (#14)
2. plugin context to load specific binds file

As for 1., can you check for me please _when_ the `.4.0.binds` file is written? Does it do it the first time you start the game with Odyssey, or only when changing something in controls options?

For 2. … first of all I’m _not_ going back to handing a path as plugin context. That is just a big no-no. If anything, I could add a dedicated plugin context that you can use for it; but honestly, I’m not sure it’s worth the effort. You have basically found the one time when it would be useful, and even then it’s only useful because the plugin hasn’t been updated for the latest expansion yet. So it’s not going to happen again for a looooong time :)

**Comment by Guntereno** [comment]
That sounds fair. I quite like the flexibility to work around such issues myself (without code modifications!), but I agree that the use case is small enough not to modify the code.

If I find time I'll do some testing on that front. However, when I started the alpha all of the new controls were automatically mapped for me. To that end I'd guess that it was written when I first opened the alpha.

**Comment by alterNERDtive** [comment]
Would have been nice to know if I can rely on immediate conversion. Guess I’ll go with the backup plan of “look for 4.0, if not there 3.0”.

**Comment by alterNERDtive** [comment]
Oh, also for future reference: do pull requests against `develop` :)

**Comment by Guntereno** [comment]
Roger that.

> 
> 
> Oh, also for future reference: do pull requests against `develop` :)

**Pull request closed without merging**
